// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitor_info.proto

#include "monitor_info.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_monitor_5finfo_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuLoad_monitor_5finfo_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_monitor_5finfo_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuStat_monitor_5finfo_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_monitor_5finfo_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SoftIrq_monitor_5finfo_2eproto;
namespace monitor {
namespace proto {
class SoftIrqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SoftIrq> _instance;
} _SoftIrq_default_instance_;
class CpuLoadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CpuLoad> _instance;
} _CpuLoad_default_instance_;
class CpuStatDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CpuStat> _instance;
} _CpuStat_default_instance_;
class MonitorInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MonitorInfo> _instance;
} _MonitorInfo_default_instance_;
}  // namespace proto
}  // namespace monitor
static void InitDefaultsscc_info_CpuLoad_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_CpuLoad_default_instance_;
    new (ptr) ::monitor::proto::CpuLoad();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuLoad_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CpuLoad_monitor_5finfo_2eproto}, {}};

static void InitDefaultsscc_info_CpuStat_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_CpuStat_default_instance_;
    new (ptr) ::monitor::proto::CpuStat();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CpuStat_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CpuStat_monitor_5finfo_2eproto}, {}};

static void InitDefaultsscc_info_MonitorInfo_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_MonitorInfo_default_instance_;
    new (ptr) ::monitor::proto::MonitorInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_MonitorInfo_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_MonitorInfo_monitor_5finfo_2eproto}, {
      &scc_info_SoftIrq_monitor_5finfo_2eproto.base,
      &scc_info_CpuLoad_monitor_5finfo_2eproto.base,
      &scc_info_CpuStat_monitor_5finfo_2eproto.base,}};

static void InitDefaultsscc_info_SoftIrq_monitor_5finfo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::monitor::proto::_SoftIrq_default_instance_;
    new (ptr) ::monitor::proto::SoftIrq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SoftIrq_monitor_5finfo_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SoftIrq_monitor_5finfo_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_monitor_5finfo_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_monitor_5finfo_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_monitor_5finfo_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_monitor_5finfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, cpu_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, hi_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, timer_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, net_tx_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, net_rx_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, block_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, irq_poll_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, tasklet_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, sched_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, hrtimer_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::SoftIrq, rcu_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, load_avg_1_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, load_avg_3_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuLoad, load_avg_15_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuStat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuStat, cpu_name_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuStat, cpu_percent_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuStat, usr_percent_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::CpuStat, system_percent_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, soft_irq_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, cpu_load_),
  PROTOBUF_FIELD_OFFSET(::monitor::proto::MonitorInfo, cpu_stat_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::monitor::proto::SoftIrq)},
  { 16, -1, sizeof(::monitor::proto::CpuLoad)},
  { 24, -1, sizeof(::monitor::proto::CpuStat)},
  { 33, -1, sizeof(::monitor::proto::MonitorInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_SoftIrq_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_CpuLoad_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_CpuStat_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::monitor::proto::_MonitorInfo_default_instance_),
};

const char descriptor_table_protodef_monitor_5finfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022monitor_info.proto\022\rmonitor.proto\032\033goo"
  "gle/protobuf/empty.proto\"\260\001\n\007SoftIrq\022\013\n\003"
  "cpu\030\001 \001(\t\022\n\n\002hi\030\002 \001(\002\022\r\n\005timer\030\003 \001(\002\022\016\n\006"
  "net_tx\030\004 \001(\002\022\016\n\006net_rx\030\005 \001(\002\022\r\n\005block\030\006 "
  "\001(\002\022\020\n\010irq_poll\030\007 \001(\002\022\017\n\007tasklet\030\010 \001(\002\022\r"
  "\n\005sched\030\t \001(\002\022\017\n\007hrtimer\030\n \001(\002\022\013\n\003rcu\030\013 "
  "\001(\002\"F\n\007CpuLoad\022\022\n\nload_avg_1\030\001 \001(\002\022\022\n\nlo"
  "ad_avg_3\030\002 \001(\002\022\023\n\013load_avg_15\030\003 \001(\002\"]\n\007C"
  "puStat\022\020\n\010cpu_name\030\001 \001(\t\022\023\n\013cpu_percent\030"
  "\002 \001(\002\022\023\n\013usr_percent\030\003 \001(\002\022\026\n\016system_per"
  "cent\030\004 \001(\002\"\213\001\n\013MonitorInfo\022(\n\010soft_irq\030\004"
  " \003(\0132\026.monitor.proto.SoftIrq\022(\n\010cpu_load"
  "\030\005 \001(\0132\026.monitor.proto.CpuLoad\022(\n\010cpu_st"
  "at\030\006 \003(\0132\026.monitor.proto.CpuStat2\235\001\n\013Grp"
  "cManager\022F\n\016SetMonitorInfo\022\032.monitor.pro"
  "to.MonitorInfo\032\026.google.protobuf.Empty\"\000"
  "\022F\n\016GetMonitorInfo\022\026.google.protobuf.Emp"
  "ty\032\032.monitor.proto.MonitorInfo\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_monitor_5finfo_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_monitor_5finfo_2eproto_sccs[4] = {
  &scc_info_CpuLoad_monitor_5finfo_2eproto.base,
  &scc_info_CpuStat_monitor_5finfo_2eproto.base,
  &scc_info_MonitorInfo_monitor_5finfo_2eproto.base,
  &scc_info_SoftIrq_monitor_5finfo_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_monitor_5finfo_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_monitor_5finfo_2eproto = {
  false, false, descriptor_table_protodef_monitor_5finfo_2eproto, "monitor_info.proto", 720,
  &descriptor_table_monitor_5finfo_2eproto_once, descriptor_table_monitor_5finfo_2eproto_sccs, descriptor_table_monitor_5finfo_2eproto_deps, 4, 1,
  schemas, file_default_instances, TableStruct_monitor_5finfo_2eproto::offsets,
  file_level_metadata_monitor_5finfo_2eproto, 4, file_level_enum_descriptors_monitor_5finfo_2eproto, file_level_service_descriptors_monitor_5finfo_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_monitor_5finfo_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_monitor_5finfo_2eproto)), true);
namespace monitor {
namespace proto {

// ===================================================================

class SoftIrq::_Internal {
 public:
};

SoftIrq::SoftIrq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:monitor.proto.SoftIrq)
}
SoftIrq::SoftIrq(const SoftIrq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  cpu_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_cpu().empty()) {
    cpu_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_cpu(), 
      GetArena());
  }
  ::memcpy(&hi_, &from.hi_,
    static_cast<size_t>(reinterpret_cast<char*>(&rcu_) -
    reinterpret_cast<char*>(&hi_)) + sizeof(rcu_));
  // @@protoc_insertion_point(copy_constructor:monitor.proto.SoftIrq)
}

void SoftIrq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SoftIrq_monitor_5finfo_2eproto.base);
  cpu_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&hi_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&rcu_) -
      reinterpret_cast<char*>(&hi_)) + sizeof(rcu_));
}

SoftIrq::~SoftIrq() {
  // @@protoc_insertion_point(destructor:monitor.proto.SoftIrq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SoftIrq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  cpu_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SoftIrq::ArenaDtor(void* object) {
  SoftIrq* _this = reinterpret_cast< SoftIrq* >(object);
  (void)_this;
}
void SoftIrq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SoftIrq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SoftIrq& SoftIrq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SoftIrq_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void SoftIrq::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.SoftIrq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cpu_.ClearToEmpty();
  ::memset(&hi_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rcu_) -
      reinterpret_cast<char*>(&hi_)) + sizeof(rcu_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SoftIrq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string cpu = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_cpu();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "monitor.proto.SoftIrq.cpu"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float hi = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          hi_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float timer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          timer_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float net_tx = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          net_tx_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float net_rx = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          net_rx_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float block = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53)) {
          block_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float irq_poll = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          irq_poll_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float tasklet = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          tasklet_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float sched = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 77)) {
          sched_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float hrtimer = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 85)) {
          hrtimer_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float rcu = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 93)) {
          rcu_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SoftIrq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.SoftIrq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cpu = 1;
  if (this->cpu().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cpu().data(), static_cast<int>(this->_internal_cpu().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "monitor.proto.SoftIrq.cpu");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_cpu(), target);
  }

  // float hi = 2;
  if (!(this->hi() <= 0 && this->hi() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_hi(), target);
  }

  // float timer = 3;
  if (!(this->timer() <= 0 && this->timer() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_timer(), target);
  }

  // float net_tx = 4;
  if (!(this->net_tx() <= 0 && this->net_tx() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_net_tx(), target);
  }

  // float net_rx = 5;
  if (!(this->net_rx() <= 0 && this->net_rx() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_net_rx(), target);
  }

  // float block = 6;
  if (!(this->block() <= 0 && this->block() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_block(), target);
  }

  // float irq_poll = 7;
  if (!(this->irq_poll() <= 0 && this->irq_poll() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_irq_poll(), target);
  }

  // float tasklet = 8;
  if (!(this->tasklet() <= 0 && this->tasklet() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_tasklet(), target);
  }

  // float sched = 9;
  if (!(this->sched() <= 0 && this->sched() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(9, this->_internal_sched(), target);
  }

  // float hrtimer = 10;
  if (!(this->hrtimer() <= 0 && this->hrtimer() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(10, this->_internal_hrtimer(), target);
  }

  // float rcu = 11;
  if (!(this->rcu() <= 0 && this->rcu() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(11, this->_internal_rcu(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.SoftIrq)
  return target;
}

size_t SoftIrq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.SoftIrq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string cpu = 1;
  if (this->cpu().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_cpu());
  }

  // float hi = 2;
  if (!(this->hi() <= 0 && this->hi() >= 0)) {
    total_size += 1 + 4;
  }

  // float timer = 3;
  if (!(this->timer() <= 0 && this->timer() >= 0)) {
    total_size += 1 + 4;
  }

  // float net_tx = 4;
  if (!(this->net_tx() <= 0 && this->net_tx() >= 0)) {
    total_size += 1 + 4;
  }

  // float net_rx = 5;
  if (!(this->net_rx() <= 0 && this->net_rx() >= 0)) {
    total_size += 1 + 4;
  }

  // float block = 6;
  if (!(this->block() <= 0 && this->block() >= 0)) {
    total_size += 1 + 4;
  }

  // float irq_poll = 7;
  if (!(this->irq_poll() <= 0 && this->irq_poll() >= 0)) {
    total_size += 1 + 4;
  }

  // float tasklet = 8;
  if (!(this->tasklet() <= 0 && this->tasklet() >= 0)) {
    total_size += 1 + 4;
  }

  // float sched = 9;
  if (!(this->sched() <= 0 && this->sched() >= 0)) {
    total_size += 1 + 4;
  }

  // float hrtimer = 10;
  if (!(this->hrtimer() <= 0 && this->hrtimer() >= 0)) {
    total_size += 1 + 4;
  }

  // float rcu = 11;
  if (!(this->rcu() <= 0 && this->rcu() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SoftIrq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.SoftIrq)
  GOOGLE_DCHECK_NE(&from, this);
  const SoftIrq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SoftIrq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.SoftIrq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.SoftIrq)
    MergeFrom(*source);
  }
}

void SoftIrq::MergeFrom(const SoftIrq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.SoftIrq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cpu().size() > 0) {
    _internal_set_cpu(from._internal_cpu());
  }
  if (!(from.hi() <= 0 && from.hi() >= 0)) {
    _internal_set_hi(from._internal_hi());
  }
  if (!(from.timer() <= 0 && from.timer() >= 0)) {
    _internal_set_timer(from._internal_timer());
  }
  if (!(from.net_tx() <= 0 && from.net_tx() >= 0)) {
    _internal_set_net_tx(from._internal_net_tx());
  }
  if (!(from.net_rx() <= 0 && from.net_rx() >= 0)) {
    _internal_set_net_rx(from._internal_net_rx());
  }
  if (!(from.block() <= 0 && from.block() >= 0)) {
    _internal_set_block(from._internal_block());
  }
  if (!(from.irq_poll() <= 0 && from.irq_poll() >= 0)) {
    _internal_set_irq_poll(from._internal_irq_poll());
  }
  if (!(from.tasklet() <= 0 && from.tasklet() >= 0)) {
    _internal_set_tasklet(from._internal_tasklet());
  }
  if (!(from.sched() <= 0 && from.sched() >= 0)) {
    _internal_set_sched(from._internal_sched());
  }
  if (!(from.hrtimer() <= 0 && from.hrtimer() >= 0)) {
    _internal_set_hrtimer(from._internal_hrtimer());
  }
  if (!(from.rcu() <= 0 && from.rcu() >= 0)) {
    _internal_set_rcu(from._internal_rcu());
  }
}

void SoftIrq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.SoftIrq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SoftIrq::CopyFrom(const SoftIrq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.SoftIrq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SoftIrq::IsInitialized() const {
  return true;
}

void SoftIrq::InternalSwap(SoftIrq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  cpu_.Swap(&other->cpu_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SoftIrq, rcu_)
      + sizeof(SoftIrq::rcu_)
      - PROTOBUF_FIELD_OFFSET(SoftIrq, hi_)>(
          reinterpret_cast<char*>(&hi_),
          reinterpret_cast<char*>(&other->hi_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SoftIrq::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class CpuLoad::_Internal {
 public:
};

CpuLoad::CpuLoad(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:monitor.proto.CpuLoad)
}
CpuLoad::CpuLoad(const CpuLoad& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&load_avg_1_, &from.load_avg_1_,
    static_cast<size_t>(reinterpret_cast<char*>(&load_avg_15_) -
    reinterpret_cast<char*>(&load_avg_1_)) + sizeof(load_avg_15_));
  // @@protoc_insertion_point(copy_constructor:monitor.proto.CpuLoad)
}

void CpuLoad::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&load_avg_1_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&load_avg_15_) -
      reinterpret_cast<char*>(&load_avg_1_)) + sizeof(load_avg_15_));
}

CpuLoad::~CpuLoad() {
  // @@protoc_insertion_point(destructor:monitor.proto.CpuLoad)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CpuLoad::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CpuLoad::ArenaDtor(void* object) {
  CpuLoad* _this = reinterpret_cast< CpuLoad* >(object);
  (void)_this;
}
void CpuLoad::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CpuLoad::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CpuLoad& CpuLoad::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CpuLoad_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void CpuLoad::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.CpuLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&load_avg_1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&load_avg_15_) -
      reinterpret_cast<char*>(&load_avg_1_)) + sizeof(load_avg_15_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CpuLoad::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float load_avg_1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          load_avg_1_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float load_avg_3 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          load_avg_3_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float load_avg_15 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          load_avg_15_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CpuLoad::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.CpuLoad)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float load_avg_1 = 1;
  if (!(this->load_avg_1() <= 0 && this->load_avg_1() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_load_avg_1(), target);
  }

  // float load_avg_3 = 2;
  if (!(this->load_avg_3() <= 0 && this->load_avg_3() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_load_avg_3(), target);
  }

  // float load_avg_15 = 3;
  if (!(this->load_avg_15() <= 0 && this->load_avg_15() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_load_avg_15(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.CpuLoad)
  return target;
}

size_t CpuLoad::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.CpuLoad)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float load_avg_1 = 1;
  if (!(this->load_avg_1() <= 0 && this->load_avg_1() >= 0)) {
    total_size += 1 + 4;
  }

  // float load_avg_3 = 2;
  if (!(this->load_avg_3() <= 0 && this->load_avg_3() >= 0)) {
    total_size += 1 + 4;
  }

  // float load_avg_15 = 3;
  if (!(this->load_avg_15() <= 0 && this->load_avg_15() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CpuLoad::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.CpuLoad)
  GOOGLE_DCHECK_NE(&from, this);
  const CpuLoad* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CpuLoad>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.CpuLoad)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.CpuLoad)
    MergeFrom(*source);
  }
}

void CpuLoad::MergeFrom(const CpuLoad& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.CpuLoad)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.load_avg_1() <= 0 && from.load_avg_1() >= 0)) {
    _internal_set_load_avg_1(from._internal_load_avg_1());
  }
  if (!(from.load_avg_3() <= 0 && from.load_avg_3() >= 0)) {
    _internal_set_load_avg_3(from._internal_load_avg_3());
  }
  if (!(from.load_avg_15() <= 0 && from.load_avg_15() >= 0)) {
    _internal_set_load_avg_15(from._internal_load_avg_15());
  }
}

void CpuLoad::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.CpuLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CpuLoad::CopyFrom(const CpuLoad& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.CpuLoad)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CpuLoad::IsInitialized() const {
  return true;
}

void CpuLoad::InternalSwap(CpuLoad* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CpuLoad, load_avg_15_)
      + sizeof(CpuLoad::load_avg_15_)
      - PROTOBUF_FIELD_OFFSET(CpuLoad, load_avg_1_)>(
          reinterpret_cast<char*>(&load_avg_1_),
          reinterpret_cast<char*>(&other->load_avg_1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CpuLoad::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class CpuStat::_Internal {
 public:
};

CpuStat::CpuStat(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:monitor.proto.CpuStat)
}
CpuStat::CpuStat(const CpuStat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  cpu_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_cpu_name().empty()) {
    cpu_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_cpu_name(), 
      GetArena());
  }
  ::memcpy(&cpu_percent_, &from.cpu_percent_,
    static_cast<size_t>(reinterpret_cast<char*>(&system_percent_) -
    reinterpret_cast<char*>(&cpu_percent_)) + sizeof(system_percent_));
  // @@protoc_insertion_point(copy_constructor:monitor.proto.CpuStat)
}

void CpuStat::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CpuStat_monitor_5finfo_2eproto.base);
  cpu_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&cpu_percent_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&system_percent_) -
      reinterpret_cast<char*>(&cpu_percent_)) + sizeof(system_percent_));
}

CpuStat::~CpuStat() {
  // @@protoc_insertion_point(destructor:monitor.proto.CpuStat)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CpuStat::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  cpu_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void CpuStat::ArenaDtor(void* object) {
  CpuStat* _this = reinterpret_cast< CpuStat* >(object);
  (void)_this;
}
void CpuStat::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CpuStat::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CpuStat& CpuStat::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CpuStat_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void CpuStat::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.CpuStat)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cpu_name_.ClearToEmpty();
  ::memset(&cpu_percent_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&system_percent_) -
      reinterpret_cast<char*>(&cpu_percent_)) + sizeof(system_percent_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CpuStat::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string cpu_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_cpu_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "monitor.proto.CpuStat.cpu_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float cpu_percent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          cpu_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float usr_percent = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          usr_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float system_percent = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          system_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CpuStat::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.CpuStat)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cpu_name = 1;
  if (this->cpu_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_cpu_name().data(), static_cast<int>(this->_internal_cpu_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "monitor.proto.CpuStat.cpu_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_cpu_name(), target);
  }

  // float cpu_percent = 2;
  if (!(this->cpu_percent() <= 0 && this->cpu_percent() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_cpu_percent(), target);
  }

  // float usr_percent = 3;
  if (!(this->usr_percent() <= 0 && this->usr_percent() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_usr_percent(), target);
  }

  // float system_percent = 4;
  if (!(this->system_percent() <= 0 && this->system_percent() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_system_percent(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.CpuStat)
  return target;
}

size_t CpuStat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.CpuStat)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string cpu_name = 1;
  if (this->cpu_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_cpu_name());
  }

  // float cpu_percent = 2;
  if (!(this->cpu_percent() <= 0 && this->cpu_percent() >= 0)) {
    total_size += 1 + 4;
  }

  // float usr_percent = 3;
  if (!(this->usr_percent() <= 0 && this->usr_percent() >= 0)) {
    total_size += 1 + 4;
  }

  // float system_percent = 4;
  if (!(this->system_percent() <= 0 && this->system_percent() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CpuStat::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.CpuStat)
  GOOGLE_DCHECK_NE(&from, this);
  const CpuStat* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CpuStat>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.CpuStat)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.CpuStat)
    MergeFrom(*source);
  }
}

void CpuStat::MergeFrom(const CpuStat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.CpuStat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cpu_name().size() > 0) {
    _internal_set_cpu_name(from._internal_cpu_name());
  }
  if (!(from.cpu_percent() <= 0 && from.cpu_percent() >= 0)) {
    _internal_set_cpu_percent(from._internal_cpu_percent());
  }
  if (!(from.usr_percent() <= 0 && from.usr_percent() >= 0)) {
    _internal_set_usr_percent(from._internal_usr_percent());
  }
  if (!(from.system_percent() <= 0 && from.system_percent() >= 0)) {
    _internal_set_system_percent(from._internal_system_percent());
  }
}

void CpuStat::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.CpuStat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CpuStat::CopyFrom(const CpuStat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.CpuStat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CpuStat::IsInitialized() const {
  return true;
}

void CpuStat::InternalSwap(CpuStat* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  cpu_name_.Swap(&other->cpu_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CpuStat, system_percent_)
      + sizeof(CpuStat::system_percent_)
      - PROTOBUF_FIELD_OFFSET(CpuStat, cpu_percent_)>(
          reinterpret_cast<char*>(&cpu_percent_),
          reinterpret_cast<char*>(&other->cpu_percent_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CpuStat::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class MonitorInfo::_Internal {
 public:
  static const ::monitor::proto::CpuLoad& cpu_load(const MonitorInfo* msg);
};

const ::monitor::proto::CpuLoad&
MonitorInfo::_Internal::cpu_load(const MonitorInfo* msg) {
  return *msg->cpu_load_;
}
MonitorInfo::MonitorInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  soft_irq_(arena),
  cpu_stat_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:monitor.proto.MonitorInfo)
}
MonitorInfo::MonitorInfo(const MonitorInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      soft_irq_(from.soft_irq_),
      cpu_stat_(from.cpu_stat_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_cpu_load()) {
    cpu_load_ = new ::monitor::proto::CpuLoad(*from.cpu_load_);
  } else {
    cpu_load_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:monitor.proto.MonitorInfo)
}

void MonitorInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MonitorInfo_monitor_5finfo_2eproto.base);
  cpu_load_ = nullptr;
}

MonitorInfo::~MonitorInfo() {
  // @@protoc_insertion_point(destructor:monitor.proto.MonitorInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MonitorInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete cpu_load_;
}

void MonitorInfo::ArenaDtor(void* object) {
  MonitorInfo* _this = reinterpret_cast< MonitorInfo* >(object);
  (void)_this;
}
void MonitorInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MonitorInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MonitorInfo& MonitorInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MonitorInfo_monitor_5finfo_2eproto.base);
  return *internal_default_instance();
}


void MonitorInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:monitor.proto.MonitorInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  soft_irq_.Clear();
  cpu_stat_.Clear();
  if (GetArena() == nullptr && cpu_load_ != nullptr) {
    delete cpu_load_;
  }
  cpu_load_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MonitorInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .monitor.proto.SoftIrq soft_irq = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_soft_irq(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // .monitor.proto.CpuLoad cpu_load = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_cpu_load(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .monitor.proto.CpuStat cpu_stat = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_cpu_stat(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MonitorInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitor.proto.MonitorInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .monitor.proto.SoftIrq soft_irq = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_soft_irq_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_soft_irq(i), target, stream);
  }

  // .monitor.proto.CpuLoad cpu_load = 5;
  if (this->has_cpu_load()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::cpu_load(this), target, stream);
  }

  // repeated .monitor.proto.CpuStat cpu_stat = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_cpu_stat_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_cpu_stat(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitor.proto.MonitorInfo)
  return target;
}

size_t MonitorInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitor.proto.MonitorInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .monitor.proto.SoftIrq soft_irq = 4;
  total_size += 1UL * this->_internal_soft_irq_size();
  for (const auto& msg : this->soft_irq_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .monitor.proto.CpuStat cpu_stat = 6;
  total_size += 1UL * this->_internal_cpu_stat_size();
  for (const auto& msg : this->cpu_stat_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .monitor.proto.CpuLoad cpu_load = 5;
  if (this->has_cpu_load()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *cpu_load_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MonitorInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:monitor.proto.MonitorInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const MonitorInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MonitorInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:monitor.proto.MonitorInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:monitor.proto.MonitorInfo)
    MergeFrom(*source);
  }
}

void MonitorInfo::MergeFrom(const MonitorInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:monitor.proto.MonitorInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  soft_irq_.MergeFrom(from.soft_irq_);
  cpu_stat_.MergeFrom(from.cpu_stat_);
  if (from.has_cpu_load()) {
    _internal_mutable_cpu_load()->::monitor::proto::CpuLoad::MergeFrom(from._internal_cpu_load());
  }
}

void MonitorInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:monitor.proto.MonitorInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MonitorInfo::CopyFrom(const MonitorInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitor.proto.MonitorInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MonitorInfo::IsInitialized() const {
  return true;
}

void MonitorInfo::InternalSwap(MonitorInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  soft_irq_.InternalSwap(&other->soft_irq_);
  cpu_stat_.InternalSwap(&other->cpu_stat_);
  swap(cpu_load_, other->cpu_load_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MonitorInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace monitor
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::monitor::proto::SoftIrq* Arena::CreateMaybeMessage< ::monitor::proto::SoftIrq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitor::proto::SoftIrq >(arena);
}
template<> PROTOBUF_NOINLINE ::monitor::proto::CpuLoad* Arena::CreateMaybeMessage< ::monitor::proto::CpuLoad >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitor::proto::CpuLoad >(arena);
}
template<> PROTOBUF_NOINLINE ::monitor::proto::CpuStat* Arena::CreateMaybeMessage< ::monitor::proto::CpuStat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitor::proto::CpuStat >(arena);
}
template<> PROTOBUF_NOINLINE ::monitor::proto::MonitorInfo* Arena::CreateMaybeMessage< ::monitor::proto::MonitorInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitor::proto::MonitorInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
